package fi.utu.tech.telephonegame;

import java.util.ArrayList;

import fi.utu.tech.telephonegame.network.Resolver;
import fi.utu.tech.telephonegame.network.Resolver.NetworkType;
import fi.utu.tech.telephonegame.ui.MainViewController;

/**
 * Do not edit this file. Älä muokkaa tätä tiedostoa.
 * 
 * The idea of this class is to provide is abstraction between UI and business logic.
 * 
 * It is used to send data to the UI and to receive events created by user.
 * The events are passed to MessageBroker.
 * 
 */

public class GuiIO {

	private MainViewController controller;
	private MessageBroker broker;

	public GuiIO(MainViewController controller) {
		this.controller = controller;
	}

	/**
	 * Add message to the list of messages shown in user interface 
	 * 
	 * @param receivedMessage The received message before it was refined
	 * @param refinedMessage The refined message which will be sent to neighbours
	 * @param hopCount The amount of hops the message has taken so far to reach this node
	 */
	public void addMessageToChatBox(String receivedMessage, String refinedMessage, Integer hopCount) {
		controller.addMessage(receivedMessage, refinedMessage, hopCount);
	}
	
	// Method below this point are not needed in the assignment. They are only used by the templete.
	
	public void enableConnect() {
		controller.enableConnect();
	}
	
	public void setMessageBroker(MessageBroker broker) {
		this.broker = broker;
	}
	
	public void sendNewMessage(String text) {
		broker.send(text);
	}

	public void connect(NetworkType netType, boolean rootNode, String rootIPAddress) {
		broker.connect(netType, rootNode, rootIPAddress);
	}

	public ArrayList<String> getIPs() {
		return Resolver.getIPs();
	}
}
